config/routes.rb
Rails.application.routes.draw do
  root to: 'home#welcome'
  get '/apply', to: 'home#apply'
  get '/faq', to: 'home#faq'
  resources :applicant
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base

    validates :name, presence: true

end

app/controllers/applicant_controller.rb
class ApplicantController < ApplicationController

  def new

  end

  def create
    @applicant = Applicant.new(applicant_params)
    if @applicant.valid?
      @applicant.save
      flash[:notice] = "Congratulations and Thank you for your application. Someone will be in touch with you shortly."
      redirect_to apply_path
    else
      flash[:error] = "There has been an error. Please try again."
      redirect_to apply_path
    end
  end

  private
  def applicant_params
    params.require(:applicant).permit(:name, :email, :phone, :movein_date, :linkedin, :facebook, :twitter)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome

  end

  def apply
    @applicant = Applicant.new
  end

  def faq

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/apply.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 red-text error-section">
      <%= flash[:notice] %><br>
      <%= flash[:error] %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 small-section">
      <h1>Apply to Live in The Negev</h1>
    </div>
  </div>
  <%= image_tag "clipboard.svg", id: 'clipboard', class: 'small-section' %>
  <div class="row">
    <div class="small-section">
      <h2>The Application Process</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <p>We have a comprehensive application process to ensure that the people living in The Negev houses are the best of the best. The first step of the application process is to fill out our application form. Once that is done someone will contact you to set up a video interview.</p>
      <p>We filter out a large number of people after the video interivew. If you made the cut to the next round, you will be invited to the house for one of our events. We will get a chance to meet you, and you'll have an opportunity to meet us.</p>
      <p>The last step of our process is for everyone currently living in the house to vote in all the new roommates. If your future roommates like you and want to live with you, you're in!</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <button class="btn" id="showApplication">Apply Now!</button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 small-section" id="app-form">
      <%= form_for @applicant, url: {action: 'create', controller: 'applicant'} do |f| %>
        <%= f.label :name %> <br>
        <%= f.text_field :name %> <br>

        <%= f.label :email %> <br>
        <%= f.email_field :email %> <br>

        <%= f.label :phone %> <br>
        <%= f.telephone_field :phone %> <br>

        <%= f.label :movein_date %> <br>
        <%= f.date_field :movein_date %> <br>

        <%= f.label :linkedin %> <br>
        <%= f.text_field :linkedin %> <br>

        <%= f.label :facebook %> <br>
        <%= f.text_field :facebook %> <br>

        <%= f.label :twitter %> <br>
        <%= f.text_field :twitter %> <br>
        <br>
        <%= f.submit 'Submit' %> <br>
      <% end %>
    </div>
  </div>
</div>

app/views/home/faq.html.erb
<div class="container">
  <div class="row first-section">
    <div class="col-md-12">
      Frequently Asked Questions
    </div>
  </div>
  <div class="row section-faq">
    <div class="col-md-7 col-md-offset-2">
      <p class="faq-question" id="question-one" data-num="1">Is The Negev house actually in the negev?</p>
      <p class="faq-answer" id="answer-1">No. The Negev houses are all in Northern California. The actual Negev is in Southern Israel.</p>

      <p class="faq-question" id="question-two" data-num="2">Do I have to be in the tech world to live in The Negev?</p>
      <p class="faq-answer" id="answer-2">Yes. All members of The Negev are in tech.</p>

      <p class="faq-question" id="question-two" data-num="3">When will you build Negev houses outside of California?</p>
      <p class="faq-answer" id="answer-3">For the moment all three of our houses are in California. We have plans to expand in the future, but not for a few years. For more information contact <a href="mailto:dannyjhaber@gmail.com">Danny Haber.</a></p>
    </div>
  </div>
</div>

app/views/home/welcome.html.erb
<div class="container">
  <div class="row first-section">
    <div class="col-md-5 col-md-offset-1">
      <%= image_tag "novel.jpg" %>
    </div>
    <div class="col-md-5 ">
      <h2>A Novel Way to Live in Cities</h2>
      <p>The Negev is a one-of-a-kind house. It's communal living 2.0. Live with like-minded individuals in a place managed through technology. Live with great people, come to our hosted parties and events and get perks that only coders and engineers would appreciate.</p>
      <%= button_to 'APPLY NOW', apply_path, class: 'btn', id: 'apply-button', method: 'get' %>
    </div>
  </div>

  <div class="row section">
    <div class="col-md-5 col-md-offset-1">
      <h2>Instant Community</h2>
      <p>At The Negev, we interview and screen every roommate to ensure that everyone here is awesome. When you move into The Negev you will have an instant community of great friends and smart people to do fun things with. We host house BBQs, parties, tech talks, family-style dinners and more.</p>
    </div>
    <div class="col-md-5 ">
      <%= image_tag "community3.jpg" %>
    </div>
  </div>

  <div class="row section">
    <div class="col-md-5 col-md-offset-1">
      <%= image_tag "roommates.jpg" %>
    </div>
    <div class="col-md-5">
      <h2>Who We Are</h2>
      <p>All roomates are in tech. Everybody has passed interviews and each person is friendly and up to something interesting. You can code with an engineer who worked at Google, a former astronaut, and even The Fonz! The Negev is a place for engineers and designers from all around the world to live, work and be social together in the great city of San Francisco.</p>
    </div>
  </div>

  <div class="row section">
    <div class="col-md-5 col-md-offset-1">
      <h2>Amenities</h2>
      <p>When you move into a Negev house you get world-class amenities. We have pool tables, a movie theater, a large co-working space, a lounge, an awesome kitchen an cool workspaces. At The Negev, you'll belong.</p>
    </div>
    <div class="col-md-5 ">
      <%= image_tag "house.jpg" %>
    </div>
  </div>

</div>

<div class="container houses-section">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>The Houses</h2>
      <p>We currently have three locations in and around the San Francisco area. Click on a house below for more information about that location.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <div class="get-container ">
        <div class="get-list single">
          <div class="span-img">
            <%= image_tag "thenegev.png" %>
          </div> <!-- END FIRST HOUSE IMAGE -->
          <div class="span-btn">
            <button class="btn-houses btn">The Negev</button>
          </div> <!-- END FIRST HOUSE BUTTON -->
        </div> <!-- END FIRST HOUSE -->
        <div class="get-list single">
          <div class="span-img">
            <%= image_tag "folsom.png" %>
          </div> <!-- END SECOND HOUSE IMAGE -->
          <div class="span-btn">
            <button class="btn-houses btn">Negev Folsom</button>
          </div> <!-- END SECOND HOUSE BUTTON -->
        </div> <!-- END SECOND HOUSE -->
        <div class="get-list single list-last">
          <div class="span-img">
            <%= image_tag "sixth_street.png" %>
          </div> <!-- END LAST HOUSE IMAGE -->
          <div class="span-btn">
            <button class="btn-houses btn">Negev 6th Street</button>
          </div> <!-- END LAST HOUSE BUTTON -->
        </div> <!-- END LAST HOUSE -->
      </div> <!-- END GET CONTAINER -->
    </div>
  </div>
</div>
<div class="bottom-margin"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Negev: A Novel Way To Live In Cities</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid header">
    <div class="row">
      <div class="col-md-5">
        <a href="<%= root_path %>"><h2>THE NEGEV</h2></a>
      </div>
      <div class="col-md-3 align-right top-margin">
        <p class="black-link"><a href="<%= faq_path %>">FAQ</a></p>
      </div>
      <div class="col-md-2 align-right">
        <%= button_to 'APPLY', apply_path, class: 'btn', id: 'top-apply', method: 'get' %>
      </div>
    </div>
  </div>
<%= yield %>

</body>
</html>